<a href="https://colab.research.google.com/github/AMOGH-DS02/FundamentalsOfDataScience_AMOGH-PARWATKAR/blob/main/08_3DMatrix_12_08_2024/08_3DMatrix_12_08_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np

def generate_matrix(seed, shape, low, high):
    np.random.seed(seed)
    return np.random.randint(low, high, size=shape)

def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

def replace_matrix_values(matrix):
    new_matrix = np.zeros_like(matrix)

    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            for k in range(matrix.shape[2]):
                value = matrix[i, j, k]

                condition_0 = (i % 2 != 0)  # Index 0 is odd
                condition_1 = is_prime(k)  # Index 1 is prime
                condition_2 = (j % 2 == 0)  # Index 2 is even

                if condition_0 and condition_1 and condition_2:
                    new_matrix[i, j, k] = 1
                else:
                    new_matrix[i, j, k] = 0

    return new_matrix

def find_longest_segment(matrix):
    longest_length = 0
    longest_coords = None
    direction = None

    # Check horizontal segments
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            length = 0
            start_col = 0
            for k in range(matrix.shape[2]):
                if matrix[i, j, k] == 1:
                    if length == 0:
                        start_col = k
                    length += 1
                else:
                    if length > longest_length:
                        longest_length = length
                        longest_coords = (i, j, start_col)
                        direction = "horizontal"
                    length = 0
            if length > longest_length:
                longest_length = length
                longest_coords = (i, j, start_col)
                direction = "horizontal"

    # Check vertical segments
    for i in range(matrix.shape[0]):
        for k in range(matrix.shape[2]):
            length = 0
            start_row = 0
            for j in range(matrix.shape[1]):
                if matrix[i, j, k] == 1:
                    if length == 0:
                        start_row = j
                    length += 1
                else:
                    if length > longest_length:
                        longest_length = length
                        longest_coords = (i, start_row, k)
                        direction = "vertical"
                    length = 0
            if length > longest_length:
                longest_length = length
                longest_coords = (i, start_row, k)
                direction = "vertical"

    return longest_length, longest_coords, direction

def main():
    # Define parameters
    seed = 49
    shape = (7, 7, 7)
    low = 0
    high = 20

    # Generate the matrix
    matrix = generate_matrix(seed, shape, low, high)
    print("Original matrix:")
    print(matrix)

    # Replace values in the matrix
    new_matrix = replace_matrix_values(matrix)
    print("\nModified matrix:")
    print(new_matrix)

    # Find the longest segment
    longest_length, longest_coords, direction = find_longest_segment(new_matrix)

    print(f"\nLongest segment length: {longest_length}")
    print(f"Coordinates of the start of the longest segment: {longest_coords}")
    print(f"Direction of the longest segment: {direction}")

if __name__ == "__main__":
    main()


Original matrix:
[[[10 13  8 18 12  5  5]
  [17 18  4 12  0 18  3]
  [ 6  1  6  4 15 15  8]
  [ 3  8  9  4 12  4  5]
  [ 7 13  1 13  6 11 13]
  [ 5 10  2  3  9 16  2]
  [ 0  8  5  5  3  2  7]]

 [[18  3  2  5  7 17 14]
  [ 4  6  5  7  2 10 10]
  [12 15 10 15 17  3 11]
  [19  5 15 13  9  8  8]
  [11 15 11  7 16  9  6]
  [17  0  2 18  0  9  3]
  [ 2  7 14 15 16 13  2]]

 [[ 1 10 16 11  3  3  5]
  [ 0  1 18  9 10 18 16]
  [ 9  3  1 12 19 17 17]
  [ 0 12  0  0  0  2 17]
  [12  7 10 19 14 15 19]
  [ 0 10  0  1 15  8  8]
  [18 11  0 18 19  4 12]]

 [[15 18  4  2 14  6  0]
  [ 4  8 11 17 11 16 16]
  [18  2  0 10  2  4 10]
  [ 2 12 10 16  1 13 10]
  [ 6  7  1  0  2 19 10]
  [19 13  0 12  1 19  0]
  [ 9  6 15 16 14  2  6]]

 [[11 13 13 12 18  5 18]
  [19  5 10  2  7  6 13]
  [ 5 19  7 10  4  7 14]
  [11 17 16 19  3  9 13]
  [15 16  3  4 10 19  5]
  [ 0  3 18 19  4 11 13]
  [ 7  6 17 19  1  1  2]]

 [[15  4  7  2 12 18  7]
  [12  8  5  5 18  3  1]
  [ 0 11  6 19  4  6  6]
  [11  2 12 15 16  6 10